package com.linguachat.version;

/**
 * Version constants generated by Stonecutter at build time.
 * These constants reflect the target Minecraft version for this build.
 */
public class VersionConstants {
    // Stonecutter will inject the actual version at build time
    /*? if >=1.21.1 {*/
    public static final String MINECRAFT_VERSION = "1.21.11";
    public static final int MINECRAFT_VERSION_MAJOR = 1;
    public static final int MINECRAFT_VERSION_MINOR = 21;
    public static final int MINECRAFT_VERSION_PATCH = 11;
    /*?} elif >=1.20.1 {*/
    /*public static final String MINECRAFT_VERSION = "1.20.1";
    public static final int MINECRAFT_VERSION_MAJOR = 1;
    public static final int MINECRAFT_VERSION_MINOR = 20;
    public static final int MINECRAFT_VERSION_PATCH = 1;
    *//*?} elif >=1.19.2 {*/
    /*public static final String MINECRAFT_VERSION = "1.19.2";
    public static final int MINECRAFT_VERSION_MAJOR = 1;
    public static final int MINECRAFT_VERSION_MINOR = 19;
    public static final int MINECRAFT_VERSION_PATCH = 2;
    *//*?} elif >=1.18.2 {*/
    /*public static final String MINECRAFT_VERSION = "1.18.2";
    public static final int MINECRAFT_VERSION_MAJOR = 1;
    public static final int MINECRAFT_VERSION_MINOR = 18;
    public static final int MINECRAFT_VERSION_PATCH = 2;
    *//*?} else {*/
    /*public static final String MINECRAFT_VERSION = "1.16.5";
    public static final int MINECRAFT_VERSION_MAJOR = 1;
    public static final int MINECRAFT_VERSION_MINOR = 16;
    public static final int MINECRAFT_VERSION_PATCH = 5;
    *//*?}*/
    
    private VersionConstants() {
        // Utility class, no instantiation
    }
}
